version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - gosec
    - misspell
    - nilerr
    - noctx
    - revive
    - sqlclosecheck
    - staticcheck
    - err113
    - nlreturn

formatters:
  enable:
    - gofmt
    - goimports
